### ISSUE TITLE
add support for www.twitch.tv?

### ISSUE THREAD

**Issue by ghost** [luisgbr1el/cliprxyz#2]
Whenever you download a clip straight from the streamers account, the link will always be something starting with `https://www.twitch.tv/`. Then the package outputs this error.
Clip being used: `https://www.twitch.tv/brucedropemoff/clip/KitschySpeedyAnteaterTheRinger-EY92zWBphRIA5xYs`
Error: `Error: The clip was not found. Try a valid url.`

Is there anyway you can fix this?

**Comment by luisgbr1el** [comment]
### Resume
**Issue fixed!** Thanks for your report.

[Click here](https://github.com/luisgbr1el/cliprxyz/releases/tag/1.0.5) to see new release.

Type ```npm update cliprxyz``` on your console to update the package.

### Using example
![image](https://user-images.githubusercontent.com/62726888/166446563-276bf9c1-4e27-4e93-9326-cd6154b6ccaa.png)

### Result
![image](https://user-images.githubusercontent.com/62726888/166446830-47e2339c-1a95-42a1-b64e-1acb3f920e56.png)

**Comment by ghost** [comment]
Thanks!! Also when I put this command up, it sends twice, it also is very very slow. Would this be due to the package or discord..?
![image](https://user-images.githubusercontent.com/80798749/166609134-8dada034-9eda-4ae7-a846-11f0410fd424.png)

**Comment by luisgbr1el** [comment]
> Thanks!! Also when I put this command up, it sends twice, it also is very very slow. Would this be due to the package or discord..?
> ![image](https://user-images.githubusercontent.com/80798749/166609134-8dada034-9eda-4ae7-a846-11f0410fd424.png)
> 

I think there's a code error, not a package error.
